### ISSUE TITLE
 object Base64 is not a member of package java.util

### ISSUE THREAD

**Issue by FRVisser** [devlaam/lora_simulator#1]
On ubuntu & El Capitan mate i get the following error:

> run
> [info] Compiling 4 Scala sources and 1 Java source to /home/fokko/ttn/lora_simulator/target/scala-2.11/classes...
> [error] /home/fokko/ttn/lora_simulator/src/main/scala/helpers.scala:69: object Base64 is not a member of package java.util
> [error]   def decode64(str: String): Try[Array[Byte]]   = Try(java.util.Base64.getDecoder.decode(str))
> [error]                                                                 ^
> [error] /home/fokko/ttn/lora_simulator/src/main/scala/helpers.scala:70: object Base64 is not a member of package java.util
> [error]   def encode64(array: Array[Byte]): Try[String] = Try(java.util.Base64.getEncoder.encode(array)).map(enc => new String(enc,0,enc.length,"UTF-8")); }
> [error]                                                                 ^
> [error] two errors found
> [error](root/compile:compileIncremental) Compilation failed

**Comment by devlaam** [comment]
I think you may need Java 8 SDK: https://docs.oracle.com/javase/8/docs/technotes/guides/lang/enhancements.html. And what is your sbt version?

**Comment by FRVisser** [comment]
I run version 0.13.9

Installing Java 8 SDK fixed the problem!

Thanks!
